server.port = 3000
spring.application.name=carehive
spring.datasource.url=jdbc:mysql://localhost:3306/carehive
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carehiveb@gmail.com
spring.mail.password=gvoz dnbn iymt osbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#jwt.secret=${JWT_SECRET}
jwt.secret=t5I3NmBxUb/0B/qzqIGVnCWFj9DKXhioRIvRQTOQRXA=

